# Generated by Django 6.0.2 on 2026-02-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="vibe",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
