# Generated by Django 6.0.2 on 2026-02-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0002_tweet_vibe"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="authenticity_score",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="tweet",
            name="fact_check_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tweet",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
